// angular/TPFinal/src/app/pages/registro/registro.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';

@Component({
  selector: 'app-registro',
  templateUrl: './registro.component.html',
  styleUrls: ['./registro.component.css']
})
export class RegistroComponent implements OnInit {

  formularioDeRegistro:FormGroup

  constructor(private fb:FormBuilder) {
    this.formularioDeRegistro = this.fb.group({
      nombre: ['', Validators.required],
      apellido: ['', Validators.required] ,
      telefono: '',
      email: ['', Validators.required],
      password: ['', [Validators.required, Validators.maxLength(10), Validators.minLength(6)]]
    })
  }

  ngOnInit(): void {
  }
}

<h1>Registrase</h1>

<form [formGroup]='formularioDeRegistro'>
  <div>
    <label>Nombre</label>
    <input type='text' formControlName='nombre'>
    <div *ngIf="formularioDeRegistro.get('nombre').errors && formularioDeRegistro.get('nombre').dirty">
      <p>El campo es obligatorio</p>
    </div>
  </div>

  <div>
    <label>Apellido</label>
    <input type='text' formControlName='apellido'>
    <div *ngIf="formularioDeRegistro.get('apellido').errors && formularioDeRegistro.get('apellido').dirty">
      <p>El campo es obligatorio</p>
    </div>
  </div>

  <div>
    <label>Teléfono</label>
    <input type='text' formControlName='telefono'>
  </div>

  <div>
    <label>Email</label>
    <input type='email' formControlName='email'>
    <div *ngIf="formularioDeRegistro.get('email').errors && formularioDeRegistro.get('email').dirty">
      <p *ngIf="formularioDeRegistro.get('email').hasError('required')">El campo es obligatorio</p>
    </div>

  </div>

  <div>
    <label>Contraseña</label>
    <input type='password' formControlName='password'>

    <div *ngIf="formularioDeRegistro.get('password').dirty && formularioDeRegistro.get('password').errors">
      <p *ngIf="formularioDeRegistro.get('password').hasError('required')">El campo es obligatorio</p>
      <p *ngIf="formularioDeRegistro.get('password').hasError('minlength')">La contraseña debe tener al menos 6 caracteres</p>
      <p *ngIf="formularioDeRegistro.get('password').hasError('maxlength')">La contraseña debe tener como máximo 10 caracteres</p>
    </div>
  </div>

  <input type='submit' value='Registrarse'>
</form>

// react/modulo1/unidad4/src/Registro.js
import React, { Component } from 'react'

class Registro extends React.Component {
  render (){
    return(
      <form>
        <label>
          Nombre:
          <input type="text" name="nombre" />
        </label>

        <label>
          Apellido:
          <input type="text" name="apellido" />
        </label>
   
        <label>
          Email:
          <input type="email" name="email" />
        </label>

        <label>
          Teléfono
          <input type="text" name="telefono" />
        </label>

        <label>
          Contraseña
          <input type="password" name="contrasena" />
        </label>

        <label>
          Reescribir contraseña
          <input type="password" name="contrasena-confirm" />
        </label>


      <input type="submit" value="Submit" />
     </form>
    )
  }
}

export default Registro;
